es_equipo_espanol(barcelona).
es_equipo_espanol(real_madrid).
es_equipo_espanol(atletico_madrid).
es_equipo_espanol(valencia).
es_equipo_espanol(sevilla).
es_equipo_espanol(villarreal).
es_equipo_espanol(real_betis).
es_equipo_espanol(athletic_bilbao).
es_equipo_holandes(ajax_amsterdams).
es_equipo_holandes(psv_eindhoven).
es_equipo_holandes(feyenoord_rotterdam).
es_equipo_holandes(az_alkmaar).
es_equipo_aleman(bayern_munich, alemania).
es_equipo_aleman(borussia_dortmund).
es_equipo_aleman(schalke_04).
es_equipo_aleman(rasenballsport_leipzig).
es_equipo_aleman(werder_bremen).
es_equipo_aleman(hamburger_sv).
es_equipo_aleman(hoffenheim).
es_equipo_italiano(juventus_turin).
es_equipo_italiano(ac_milan).
es_equipo_italiano(inter_milan).
es_equipo_italiano(roma).
es_equipo_italiano(napoli).
es_equipo_italiano(lazio_roma).
es_equipo_italiano(fiorentina).
es_equipo_italiano(atalanta_bergamo).
es_equipo_ingles(chelsea).
es_equipo_ingles(manchester_united).
es_equipo_ingles(manchester_city).
es_equipo_ingles(arsenal).
es_equipo_ingles(liverpool).
es_equipo_ingles(tottenham_hotspur).
es_equipo_ingles(leicester_city).
es_equipo_ingles(west_ham_united).
es_equipo_frances(paris_saint_germain).
es_equipo_frances(olympique_lyonnais).
es_equipo_frances(olympique_de_marsella).
es_equipo_frances(as_monaco).
es_equipo_frances(lille_losc).
es_equipo_frances(stade_rennais).
es_equipo_frances(bordeaux_girondins).
es_equipo_frances(nantes).
es_equipo_portugues(benfica).
es_equipo_portugues(orto).
es_equipo_portugues(sporting_lisboa).
es_equipo_portugues(braga).
es_equipo_portugues(pacos_ferreira).
es_equipo_portugues(vitoria_guimaraes).
es_equipo_portugues(boavista).
es_equipo_portugues(tondela).
es_equipo_argentino(river_plate).
es_equipo_argentino(boca_juniors).
es_equipo_argentino(independiente).
es_equipo_argentino(racing_club).
es_equipo_argentino(velez).
es_equipo_argentino(rosario_central).
es_equipo_argentino(estudiantes).
es_equipo_argentino(newells).
es_equipo_brasileno(flamengo).
es_equipo_brasileno(palmeiras).
es_equipo_brasileno(sao_paulo).
es_equipo_brasileno(corinthians).
es_equipo_brasileno(santos).
es_equipo_brasileno(internacional).
es_equipo_brasileno(gremio).
es_equipo_brasileno(atletico_mineiro).
es_equipo_mexicano(cruz_azul).
es_equipo_mexicano(america).
es_equipo_mexicano(guadalajara).
es_equipo_mexicano(tigres_uanl).
es_equipo_mexicano(monterrey).
es_equipo_mexicano(toluca).
es_equipo_mexicano(pachuca).
es_equipo_mexicano(queretaro).